stages:
  - build_image
  - test
  - deploy

variables:
  BUILD_DOCKER_IMAGE: "false"

build docker image:
  rules:
    - if: $BUILD_DOCKER_IMAGE == "true"
  stage: build_image
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

run unit tests:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - ./scripts/setup-venv.sh
    - ./scripts/ci-test.sh
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    when: always
    paths:
      - coverage/test-report.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
      junit: coverage/test-report.xml

Test Python 3.8:
  stage: test
  image: python:3.8
  script:
    - ./scripts/install-deps.sh
    - ./scripts/setup-venv.sh
    - ./scripts/ci-test.sh

Test Python 3.9:
  stage: test
  image: python:3.9
  script:
    - ./scripts/install-deps.sh
    - ./scripts/setup-venv.sh
    - ./scripts/ci-test.sh

Test Python 3.10:
  stage: test
  image: python:3.10
  script:
    - ./scripts/install-deps.sh
    - ./scripts/setup-venv.sh
    - ./scripts/ci-test.sh

pages:
  stage: deploy
  image: $CI_REGISTRY_IMAGE
  script:
    - ./scripts/setup-venv.sh
    - ./scripts/build-docs.sh
    - cp -r docs/build/public/ public
  artifacts:
    paths:
      - public
  only:
    - master