stages:
  - build_image
  - test

variables:
  BUILD_DOCKER_IMAGE: "false"

build docker image:
  rules:
    - if: $BUILD_DOCKER_IMAGE == "true"
  stage: build_image
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

run unit tests:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - ./scripts/setup-venv.sh
    - source venv/bin/activate
    - ./scripts/ci-test.sh