stages:
  - build_image
  - test
  - build_docs

build docker image:
  stage: build_image
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

run unit tests:
  stage: test
  image: $CI_REGISTRY_IMAGE
  needs:
    - build docker image
  script:
    - ./scripts/setup-venv.sh
    - source venv/bin/activate
    - ./scripts/run-tests.sh

docs:
  stage: build_docs
  image: $CI_REGISTRY_IMAGE
  needs:
    - build docker image
  script:
    - ./scripts/setup-venv.sh
    - source venv/bin/activate
    - ./scripts/build-docs.sh