name: Nightly CI Test Pipeline

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_test:
    uses: ./.github/workflows/build-test-workflow.yaml

  docker_deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run build script
      run: |
        cd docker 
        chmod +x build.sh
        ./build.sh ${{ github.sha }}

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}